name: Red Hat JBoss Fuse Service Works
abbreviated_name: JBoss Fuse Service Works
forum_url: https://community.jboss.org/en/fsw
current_version: 6.0.0.GA
documentation_minor_version: 6
intro_video: https://vimeo.com/95295423
intro_video_2: https://vimeo.com/95306459
featured_videos:
    - https://vimeo.com/77941255
    - https://vimeo.com/77948747
    - https://vimeo.com/77953694
guides:
  Administration_and_Configuration_Guide:
  Development_Guide_Volume_1_SwitchYard:
    name: "Development Guide Volume 1: SwitchYard"
  Development_Guide_Volume_2_Smooks:
    name: "Development Guide Volume 2: Smooks"
  Development_Guide_Volume_3_Governance:
    name: "Development Guide Volume 3: Governance"
  Development_Guide_Volume_4_BPEL:
    name: "Development Guide Volume 4: BPEL"
  Getting_Started_Guide:
  Installation_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Fuse_Service_Works/6/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Fuse_Service_Works/6/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Fuse_Service_Works/6/pdf/Release_Notes/Red_Hat_JBoss_Fuse_Service_Works-6-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Fuse_Service_Works/6/epub/Release_Notes/Red_Hat_JBoss_Fuse_Service_Works-6-Release_Notes-en-US.epub
  Security_Guide:
  User_Guide:
downloads:
  6.0.0.GA:
    release_date: 2013-10-21
    description: A service design, development and integration platform enabling organizations to transition to open hybrid cloud.
    assets:
      zip:
        size: 412mb
        name: Jar (Installer)
upstream_projects:
  - switchyard
  - overlord
  - drools
  - riftsaw

