name: Red Hat JBoss Enterprise Application Platform
abbreviated_name: JBoss EAP
current_version: 6.3.0.Beta
has_installer: true
# EAP is still using an old name for docs on the customer portal
documentation_path: JBoss_Enterprise_Application_Platform
featured_videos:
  - http://vimeo.com/41145588
articles:
  - https://access.redhat.com/site/articles/216263
  - https://access.redhat.com/site/articles/112673
  - https://access.redhat.com/site/articles/119933
  - https://access.redhat.com/site/articles/545183
  - https://access.redhat.com/site/articles/20490
  - https://access.redhat.com/site/articles/524633
  - https://access.redhat.com/site/articles/625703
  - https://access.redhat.com/site/articles/115883
  - https://access.redhat.com/site/articles/113373
  - https://access.redhat.com/site/articles/225023
  - https://access.redhat.com/site/articles/704703
  - https://access.redhat.com/site/articles/770323
  - https://access.redhat.com/site/articles/112543
  - https://access.redhat.com/site/articles/427493
  - https://access.redhat.com/site/articles/15786
  - https://access.redhat.com/site/articles/310603
  - https://access.redhat.com/site/articles/626493
  - https://access.redhat.com/site/articles/706263
  - https://access.redhat.com/site/articles/626513
  - https://access.redhat.com/site/articles/703153
solutions:
  - https://access.redhat.com/site/solutions/36926
  - https://access.redhat.com/site/solutions/44626
  - https://access.redhat.com/site/solutions/323033
  - https://access.redhat.com/site/solutions/229963
  - https://access.redhat.com/site/solutions/60888
  - https://access.redhat.com/site/solutions/161733
  - https://access.redhat.com/site/solutions/31400
  - https://access.redhat.com/site/solutions/309913
  - https://access.redhat.com/site/solutions/32744
  - https://access.redhat.com/site/solutions/199493
  - https://access.redhat.com/site/solutions/107983
  - https://access.redhat.com/site/solutions/199493
  - https://access.redhat.com/site/solutions/414953
  - https://access.redhat.com/site/solutions/361343
  - https://access.redhat.com/site/solutions/18678
  - https://access.redhat.com/site/solutions/68614
  - https://access.redhat.com/site/solutions/341683
  - https://access.redhat.com/site/solutions/209023
  - https://access.redhat.com/site/solutions/41097
  - https://access.redhat.com/site/solutions/237933
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
      html-single:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  Security_Guide:
  Getting_Started_Guide:
# EAP has an installer, we want to default to that
default_download_artifact_type: installer
downloads:
  6.3.0.Beta:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2014-05-15
    assets:
      installer:
        size: 150mb
      zip:
        name: Zip Files
        artifacts: 
          zip:
            size: 37mb
      release_notes:
      source:
        size: 37mb
  6.2.0.GA:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2013-12-04
    assets:
      installer:
        size: 158mb
      zip:
        name: Zip Files
        artifacts: 
          zip:
            size: 34mb
      release_notes:
      source:
        size: 34mb
#  6.1.1.GA:
#    description: Minor release of JBoss EAP 6.x series
#    release_date: 2013-09-04
#    assets:
#      installer:
#        size: 150mb
#      zip:
#        size: 117mb
#      release_notes:
#      source:
#        size: 27mb
  6.1.0.GA:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2013-05-20
    assets:
      installer:
        size: 150mb
      zip:
        name: Zip Files
        artifacts:
          zip:
            size: 110mb
      release_notes:
      source:
        size: 27mb
#  6.0.1.GA:
#    description: Minor release of JBoss EAP 6.x series
#    release_date: 2013-01-23
#    assets:
#      installer:
#        size: 133mb
#      zip:
#        size: 111mb
#      release_notes:
#      source:
#        size: 21mb
#  6.0.0.GA:
#    description: Major release of JBoss EAP 6.x series
#    release_date: 2012-06-12
#    assets:
#      installer:
#        size: 129mb
#      zip:
#        size: 110mb
#      release_notes:
#      source:
#        size: 21mb
#  5.2.0.GA:
#    description: Minor release of JBoss EAP 5.x series
#    release_date: 2013-01-24
#    assets:
#      binary-installer:
#        size: 417mb
#      binary-zip:
#        size: 294mb
#      release_notes:
#      source:
#        size: 175mb
#
upstream_projects:
  - wildfly
  - jgroups
  - hibernate
  - hornetq
  - jbossclustering
  - jbossmc
  - narayana
  - jbossweb
  - jbossws
  - ironjacamar
  - jgroups
  - mod_cluster
  - jbossas_osgi
  - jbosssso
  - picketlink
  - resteasy
  - weld
  - wise
  - xnio
featured_items:
  - image_url: /images/design/devmats/developermaterials_eap.png
    title: HTML5 Mobile with EAP 6 at OpenShift
    text: Build HTML5 mobile applications with EAP 6

