:awestruct-layout: product-overview
:leveloffset: 1

== Overview

JBoss Data Virtualization is a data integration solution that sits in front of multiple data sources and allows them to be treated as a single source, delivering the right data, in the required form, at the right time to any application and/or user.

== Features1

=== Agile Development

Rapid ways to deliver reusable and loosely coupled unified data views and data services using graphical tools. Hide data integration complexity from data consuming application developers and business users. Decouple consuming applications and data sources. Allow reuse and extension of logical data models, views and services.

== Icon1

[.fa .fa-hdd-o .fa-5x .fa-fw]#&nbsp;# 

== Features2

=== Secure Virtual Data Layer

Builds powerful transformations and relationships using an integrated modeling and execution environment to transform and combine relate data across heterogeneous source types using common metadata and semantics. Apply role based data access, security and auditing policies regardless of data source types like a data firewall.

== Icon2

[.fa .fa-info-circle .fa-5x .fa-fw]#&nbsp;# 

== Features3

=== Real-time Data Access and Provisioning

Read/write from any source or data type including Legacy, NoSQL and Cloud. Expose the combined information as reusable Data Views & Data Services in multiple formats and supporting hybrid delivery modes (on-demand, cache, and materialized) to consuming applications. 
Lean Integration: Reduce data sprawl by avoiding compulsory data copying and minimize cost and risk of unnecessary data duplication, storage and management.

== Icon3

[.fa .fa-tint .fa-5x .fa-fw]#&nbsp;#


== Detail

==== For JBoss Data Virtualization 6.1 Beta, we focused on

- Big Data
- Cloud 
- Development and Deployment Improvements 

==== BIG DATA

- Support for Cloudera Impala in addition to Apache Hive
- Support for Apache Solr as a data source
- Full support for MongoDB 
- Expanded support for JDG with the ability to perform writes Apache
- Cassandra (Tech Preview)

==== CLOUD
- OpenShift Online with new WebUI (Dev Preview)
- Cloud enablement with support for Amazon EC2 and Google Compute Engine

==== PRODUCTIVITY AND DEPLOYMENT IMPROVEMENTS
- Security audit log dashboard
- Custom Translator Improvements
- Apache POI for multi-platform MS Excel deployments
- Performance Improvements
- Support for Azul Zing JVM, EAP 6.3, MariaDB

== Resources
