name: Red Hat JBoss BPM Suite
abbreviated_name: JBoss BPMSuite
has_installer: true
current_version: 6.0.1.GA
documentation_minor_version: 6.0
featured_videos:
 - http://vimeo.com/86884030
 - http://vimeo.com/87038127
 - http://vimeo.com/66311377
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/html/6.0.1_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/html-single/6.0.1_Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/pdf/6.0.1_Release_Notes/Red_Hat_JBoss_BPM_Suite-6.0-6.0.1_Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/epub/6.0.1_Release_Notes/Red_Hat_JBoss_BPM_Suite-6.0-6.0.1_Release_Notes-en-US.epub
  Administration_And_Configuration_Guide:
  Business_Resource_Planner_Guide:
  Development_Guide:
  Getting_Started_Guide:
  Installation_Guide:
  User_Guide:
  Working_with_the_BPM_Suite_Example_App:
downloads:
  6.0.1.GA:
    release_date: 2014-04-3
    assets:
      zip_supplemental:
        size: 19mb
        name: Supplemental Tools
      zip_planner:
        size: 52mb
        name: Optaplanner
      zip:
        artifacts:
          deployable:
            size: 153mb
      release_notes:
      source:
        size: 154mb



