name: Red Hat JBoss BPM Suite
abbreviated_name: JBoss BPMSuite
has_installer: true
current_version: 6.0.1.GA
documentation_minor_version: 6.0
xpaas_url: https://www.openshift.com/developers/jboss-bpms
intro_video: https://vimeo.com/95505857
vimeo_album: http://vimeo.com/album/2982446
buzz_tags: BPM Suite
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/html/6.0.1_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/html-single/6.0.1_Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/pdf/6.0.1_Release_Notes/Red_Hat_JBoss_BPM_Suite-6.0-6.0.1_Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/epub/6.0.1_Release_Notes/Red_Hat_JBoss_BPM_Suite-6.0-6.0.1_Release_Notes-en-US.epub
  Administration_And_Configuration_Guide:
  Business_Resource_Planner_Guide:
  Development_Guide:
  Getting_Started_Guide:
  Installation_Guide:
  User_Guide:
  Working_with_the_BPM_Suite_Example_App:
default_download_artifact_type: installer
downloads:
  # 6.0.1 is an exclusion to the "no micros through $0 dev program
  6.0.1.GA:
    release_date: 2014-04-03
    assets:
      installer:
        size: 312mb
      zip:
        artifacts:
          deployable:
            size: 304mb
      maven_repo:
        size: 280mb
        name: Maven Repository
      zip_planner:
        size: 53mb
        name: Optaplanner
      example:
        size: 7.8mb
        name: BPM Example
      zip_supplemental:
        size: 59mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 177mb
upstream_projects:
  - drools
  - guvnor
  - optaplanner
  - jbpm 
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_bpmsuite.png
    url: /quickstarts/brms/tasks-bpmsuite

