name: Red Hat JBoss Operations Network
abbreviated_name: JBoss Operations Network
downloads:
  3.2.0.GA:
    release_date: 2013-12-17
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      source:
        size: 28mb
      zip:
        size: 308mb
        name: Zip (Base Distribution)
  3.1.2.GA:
    release_date: 2013-01-23
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      source:
        size: 30mb
      zip:
        size: 215mb
        name: Zip (Base Distribution)
  3.1.1.GA:
    release_date: 2012-10-03
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      source:
        size: 30mb
      zip:
        size: 222mb
        name: Zip (Base Distribution)
  3.1.0.GA:
    release_date: 2012-06-12
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      source:
        size: 30mb
      zip:
        size: 222mb
        name: Zip (Base Distribution)
  3.0.1.GA:
    release_date: 2012-03-19
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      source:
        size: 27mb
      zip:
        size: 254mb
        name: Zip (Base Distribution)
  3.0.0.GA:
    release_date: 2011-12-07
    description: Provides a single of control to deploy, manage and montor your JBoss Middleware, applications and services.
    assets:
      zip:
        size: 254mb
        name: Zip (Base Distribution)
upstream_projects:

