name: Red Hat JBoss Portal
abbreviated_name: JBoss Portal
forum_url: https://community.jboss.org/en/jbossjpp
current_version: 6.1.0.GA
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:
downloads:
  6.1.0.GA:
    release_date: 2013-10-16
    description: Provides reliability and powerful performance with a track record of near-zero downtime and maintenance along with high-availability, clustering, caching, failover, load-balancing, and distributed deployment features.
    assets:
      source:
        size: 66mb
      zip:
        size: 205mb
        name: Zip (Base Distribution)
#  6.0.0.GA:
#    release_date: 2013-03-07
#    description: Provides reliability and powerful performance with a track record of near-zero downtime and maintenance along with high-availability, clustering, caching, failover, load-balancing, and distributed deployment features.
#    assets:
#      source:
#        size: 53mb
#      zip-full:
#        size: 186mb
#        name: Zip (Base Distribution)
#  5.2.2.GA:
#    release_date: 2012-09-03
#    description: Provides reliability and powerful performance with a track record of near-zero downtime and maintenance along with high-availability, clustering, caching, failover, load-balancing, and distributed deployment features.
#    assets:
#      source:
#        size: 220mb
#      zip-full:
#        size: 547mb
#        name: Zip (Base Distribution)
#  5.2.1.GA:
#    release_date: 2012-04-24
#    description: Provides reliability and powerful performance with a track record of near-zero downtime and maintenance along with high-availability, clustering, caching, failover, load-balancing, and distributed deployment features.
#    assets:
#      source:
#        size: 236mb
#      zip-full:
#        size: 548mb
#        name: Zip (Base Distribution)
#  5.2.0.GA:
#    release_date: 2011-12-14
#    description: Provides reliability and powerful performance with a track record of near-zero downtime and maintenance along with high-availability, clustering, caching, failover, load-balancing, and distributed deployment features.
#    assets:
#      source:
#        size: 210mb
#      zip-full:
#        size: 566mb
#        name: Zip (Base Distribution)
upstream_projects:
  - gatein_porletcontainer
  - gatein
featured_items:
  - image_url: /images/design/devmats/developermaterials_portal.png
    title: 
    text: Configure your portal for mobile devices


