name: Red Hat JBoss A-MQ 
abbreviated_name: JBoss A-MQ
current_version: 6.1.0.GA
documentation_path: JBoss_A-MQ
guides:
  API_Reference:
  Broker_Administration_Tutorials:
  Client_Connectivity_Guide:
  Configuring_Broker_Persistence:
  Connection_Reference:
  Console_Reference:
  Fault_Tolerant_Messaging:
  Glossary:
  Installation_Guide:
  Managing_and_Monitoring_a_Broker:
  Migration_Guide:
  Performance_Metrics_Reference:
  Release_Notes:
   formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/JBoss_A-MQ/6.0/html/Release_Notes/files/front.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/JBoss_A-MQ/6.0/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/JBoss_A-MQ/6.0/pdf/Release_Notes/JBoss_A-MQ-6.0-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/JBoss_A-MQ/6.0/epub/Release_Notes/JBoss_A-MQ-6.0-Release_Notes-en-US.epub
  Security_Guide:
  Tuning_Guide:
  Using_Networks_of_Brokers:
  Using_the_Management_Console:
  XML_Configuration_Reference:
downloads:
  6.1.0.GA:
    release_date: 2014-04-14
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size: 181mb
        name: Zip (Full Install)
      source:
        size: 81mb
  6.0.0.GA:
    release_date: 2013-04-10
    description: Our small footprint, high performance, open source messaging platform
    assets:
      zip:
        size: 209mb
        name: Zip (Full Install)
      fuse_ide:
        name: Fuse IDE
        artifacts:
          mac_osx:
            name: MacOS X
            size: 209mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-maxosx.zip
          win32:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-win32.zip
          win64:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-win64.zip
          linux32:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-linux32.zip
          linux64:
            size: 210mb
            filename: jboss-fuse-6.0.0.GA-fuse_ide-linux64.zip
      release_notes:
      source:
        size: 64mb
upstream_projects:
featured_items:
  - image_url: /images/slider-image1.jpg
    title: a new featured item, at the product level
    text: Just some random featured item text
