name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
current_version: 6.0.0.GA
documentation_minor_version: 6
xpaas_url: https://www.openshift.com/developers/jboss-data-virtualization
intro_video: https://vimeo.com/91533636
vimeo_album: http://vimeo.com/album/2982437
guides:
  Development_Guide_Reference_Material:
    name: "Development Guide: Reference Material"
  Development_Guide_Server_Development:
    name: "Development Guide: Server Development"
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/pdf/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/epub/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Release_Notes-en-US.epub
description: 'A data virtualization tool useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos. (formerly known as JBoss Enterprise Data Services Platform).'
downloads:
  6.1.0.Beta:
    release_date: 2014-11-03
    tag_line: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis velit nunc, mattis eget ligula eget, fringilla mattis erat. Proin vulputate placerat nunc, vitae aliquam mi facilisis in. Nunc cursus, velit sed tincidunt sodales, est massa porta dui, in
    description: Improved User Interface, OpenShift Beta Cartridge, Kerberos, Audit Log in Dashboard, MongoDB, Cloudera/Impala. Apache Solr, EAP 6.3, JDG 6.2.
    assets:
      zip:
        size: 290mb
        name: Jar (Installer)
        filename: jboss-dv-installer-6.1.0.ER2-redhat-1.jar
  6.0.0.GA:
    release_date: 2014-02-03
    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
    assets:
      zip:
        size: 235mb
        name: Jar (Installer)
      source:
        size: 67mb
      docker:
        name: Docker (Unsupported)
        artifacts:
          docker-src:
            url: https://github.com/JBoss-Dockerfiles/DV600Base
  6.0.0.Beta:
    release_date: 2013-10-09
    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
    assets:
      zip:
        size: 217mb
        name: Zip (Beta Installer)
      source:
        size: 39mb
upstream_projects:
  - teiid
  - teiiddesigner
  - modeshape
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datavirtualization.png
    url: /video/vimeo/76457404
    text: Launch into the virtual data world

