name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
forum_url: https://community.jboss.org/en/datavirt
current_version: 6.0.0.GA
documentation_minor_version: 6
intro_video: https://vimeo.com/91533636
featured_videos:
  - https://vimeo.com/76457404
  - https://vimeo.com/76471307
  - https://vimeo.com/76476379
guides:
  Development_Guide_Reference_Material:
    name: "Development Guide: Reference Material"
  Development_Guide_Server_Development:
    name: "Development Guide: Server Development"
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  Release_Notes:
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/pdf/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Beta-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6/epub/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6-Beta-Release_Notes-en-US.epub
downloads:
  6.0.0.GA:
    release_date: 2014-02-03
    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
    assets:
      zip:
        size: 235mb
        name: Jar (Installer)
      source:
        size: 67mb
  6.0.0.Beta:
    release_date: 2013-10-09
    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
    assets:
      zip:
        size: 217mb
        name: Zip (Beta Installer)
      source:
        size: 39mb
#  5.3.1.GA:
#    release_date: 2013-02-20
#    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
#    assets:
#      zip-lib:
#        size: 30mb
#        name: Zip (Library)
#      SOA-platform:
#        size: 637mb
#        name: Zip (Full Platform)
#      SOA-standalone:
#        size: 238mb
#        name: Zip (Standalone Platform)
#      source-dataservice:
#        size: 38mb
#      source-SOA:
#        size: 192mb
#  5.3.0.GA:
#    release_date: 2012-07-31
#    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
#    assets:
#      zip-services:
#        size: 30mb
#        name: Zip (Library)
#      source-dataservice:
#        size: 52mb
#      source-SOA:
#        size: 201mb
#      SOA-platform:
#        size: 627mb
#        name: Zip (Full Platform)
#      SOA-standalone:
#        size: 231mb
#        name: Zip (Standalone Platform)
#  5.2.0.GA:
#    release_date: 2011-11-16
#    description: Accesses and transforms data from one or more heterogeneous sources into logical, business-friendly data models.
#    assets:
#      zip-services:
#        size: 35mb
#        name: Zip (Library)
#      source-dataservice:
#        size: 52mb
#      source-SOA:
#        size: 276mb
#      SOA-Platform:
#        size: 732mb
#        name: Zip (Full Platform)
#      SOA-Standalone:
#        size: 235mb
#        name: Zip (Standalone Platform)
upstream_projects:
  - teiid
  - teiiddesigner
  - modeshape
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datavirtualization.png
    url: /video/vimeo/76457404
    text: Launch into the virtual data world

