name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
current_version: 7.1.1.GA
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
buzz_tags: jbds
guides:
  CDI_Tools_Reference_Guide:
  Getting_Started_Guide:
  Hibernate_Tools_Reference_Guide:
  Installation_Guide:
  JBoss_Portlet_Tools_User_Guide:
  JBoss_RESTful_Web_Services_User_Guide:
  JBoss_SOAP_Web_Services_User_Guide:
  JMX_Tools_Reference_Guide:
  JSF_Tools_Reference_Guide:
  JSF_Tools_Tutorial:
  Maven_Tools_Reference_Guide:
  Migration_Guide:
  Release_Notes_7.1.0:
  Seam_Developer_Tools_Reference_Guide:
  Seam_Tools_Tutorial:
  User_Guide:
  Visual_Web_Tools_Reference_Guide:
default_download_artifact_type: jar_universal
forum:
  name: jbossdevstudio
  url: https://community.jboss.org/en/jbossdevstudio
  description: 'A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.'
downloads:
  8.0.0.Beta3:
    release_date: 2014-07-28
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4 Luna.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 643mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 504mb
        type: jar
      standalone_zip_update:
        name: Update Site
        size: 850mb
        type: zip
      standalone_zip_central:
        name: JBoss Central
        size: 115mb
        type: zip
      source:
        name: Source
        size: 7.6mb
        type: zip
  8.0.0.Beta2:
    release_date: 2014-06-20
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4 Luna M7.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 676mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 550mb
        type: jar
      standalone_zip_update:
        name: Update Site
        size: 830mb
        type: zip
      standalone_zip_central:
        name: JBoss Central
        size: 115mb
        type: zip
      source:
        name: Source
        size: 6.4mb
        type: zip
  8.0.0.Beta1:
    release_date: 2014-04-11
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4 Luna M6.
    assets:
      jar_universal:
        size: 613mb
        name: Installer With EAP
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 487mb
        type: jar
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-8.0.0.Beta1-standalone_universal-standalone_jar.jar
      standalone_zip_update:
        name: Update Site
        size: 725mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-8.0.0.Beta1-standalone_universal-standalone_zip_update.zip
      standalone_zip_central:
        name: JBoss Central
        size: 420mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-8.0.0.Beta1-standalone_universal-standalone_zip_central.zip
      source:
        size: 6mb
  7.1.1.GA:
    release_date: 2014-03-26
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.3 Kepler.
    assets:
      jar_universal:
        size: 609mb
        name: Installer Jar (with EAP)
        type: jar
      standalone_jar:
        name: Installer Jar (Stand-alone)
        size: 482mb
        type: jar
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_jar.jar
      standalone_zip_update:
        name: Update Site Zip
        size: 713mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_update.zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 410mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_central.zip
      source:
        size: 6mb
#   7.1.0.GA:
#   release_date: 2013-12-16
#    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.3 Kepler.
#    assets:
#      jar_universal:
#        size: 613mb
#        name: Jar (Universal Binary with EAP)
#        type: jar
#      standalone_universal:
#        artifacts:
#          standalone_jar:
#            size: 487mb
#            type: jar
#          standalone_zip_central:
#            size: 410mb
#          standalone_zip_update:
#            size: 719mb
#      source:
#        size: 6mb
#  7.0.0.GA:
#    release_date: 2013-07-23
#    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.3 Kepler.
#    assets:
#      jar_universal:
#        size: 591mb
#        name: Jar (Universal Binary with EAP)
#      standalone_universal:
#        artifacts:
#          standalone_jar:
#            size: 481mb
#          standalone_zip_update:
#            size: 697mb
#      release_notes:
#      source:
#        size: 6mb
#  6.0.1.GA:
#    release_date: 2013-04-04
#    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.2 Juno.
#    assets:
#      jar_universal:
#        size: 566mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 455mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 111mb
#  6.0.0.GA:
#    release_date: 2012-12-07
#    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.2 Juno.
#    assets:
#      jar_universal:
#        size: 564mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 454mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 3mb
#  5.0.0.GA:
#    release_date: 2012-06-21
#    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.1 Indigo.
#    assets:
#      jar_universal:
#        size: 495mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 385mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 111mb
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627

