name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
current_version: 9.1.0.Beta1
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKrxJ9OtX2Zmgw3nyeYs0QGR
buzz_tags:
  - jbds
guides:
  Release_Notes:
  Install_Red_Hat_JBoss_Developer_Studio:
  Start_Developing:
  Update_Red_Hat_JBoss_Developer_Studio:
default_download_artifact_type: jar_universal
description: 'A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.'
downloads:
  9.1.0.Beta1:
    release_date: 2015-12-21
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.1 Mars.1.
    assets:
      jar_universal:
        name: Installer With EAP 6.4.0 CVE-2015-7501
        size: 646MB
        type: jar
        url: https://www.jboss.org/download-manager/content/origin/files/sha256/cc/cc2d921a34d22ae99ebb428325a278b8350f58f664ad556754708e282eb650f8/jboss-devstudio-9.1.0.Beta1-installer-eap.jar
      standalone_jar:
        name: Stand-alone Installer
        size: 501MB
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 523MB
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 154MB
        type: zip
      source:
        name: Source Zip
        size: 224MB
        type: zip
  9.0.0-CVE-2015-7501.GA:
    release_date: 2015-12-08
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.1 Mars.1.
    assets:
      jar_universal:
        name: Installer With EAP 6.4.0 CVE-2015-7501 (2015-12-08)
        size: 633mb
        type: jar
        url: https://www.jboss.org/download-manager/content/origin/files/sha256/1e/1efef4d2b109efd9e8136d02067a8d62e00621e5b2b1530811bf52b5aa2fca6f/jboss-devstudio-9.0.0.GA-CVE-2015-7501-installer-eap.jar
      release_notes:
        url: http://tools.jboss.org/blog/ga-cve-for-mars.html
  9.0.0.GA:
    release_date: 2015-10-06
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.1 Mars.1.
    assets:
      jar_universal:
        name: Installer With EAP 6.4.0
        size: 633mb
        type: jar
        url: https://www.jboss.org/download-manager/content/origin/files/sha256/4f/4fe77f731aa2a46a4d8568786c0c7c2d486e0926025d06a95360e9e767a2af94/jboss-devstudio-9.0.0.GA-installer-eap.jar
      standalone_jar:
        name: Stand-alone Installer
        size: 489mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 514mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 154mb
        type: zip
      source:
        name: Source Zip
        size: 223mb
        type: zip
  9.0.0.CR1:
    release_date: 2015-09-22
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.1 Mars.1.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 633mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 489mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 514mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 154mb
        type: zip
      source:
        name: Source Zip
        size: 223mb
        type: zip
  9.0.0.Beta2:
    release_date: 2015-07-29
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.0 Mars R.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 630mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 485mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 507mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 116mb
        type: zip
      source:
        name: Source Zip
        size: 333mb
        type: zip
  9.0.0.Beta1:
    release_date: 2015-06-22
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.5.0 Mars R.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 628mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 484mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 505mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 115mb
        type: zip
      source:
        name: Source Zip
        size: 292mb
        type: zip
  8.1.0.GA:
    release_date: 2015-04-02
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4.2 Luna SR2.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 706mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 576mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 528mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 296mb
        type: zip
      source:
        name: Source Zip
        size: 44mb
        type: zip
  8.1.0.CR1:
    release_date: 2015-03-19
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4.2 Luna SR2.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 685mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 546mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 523mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 295mb
        type: zip
      source:
        name: Source Zip
        size: 44mb
        type: zip
  8.1.0.Beta1:
    release_date: 2015-03-04
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4.2 Luna SR2.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 685mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 546mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 524mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 304mb
        type: zip
      source:
        name: Source Zip
        size: 42mb
        type: zip
  8.0.0.GA:
    release_date: 2014-10-21
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4.1 Luna SR1.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 687mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 548mb
        type: jar
      standalone_zip_update:
        name: Update Site Zip
        size: 516mb
        type: zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 304mb
        type: zip
      source:
        name: Source Zip
        size: 8.5mb
        type: zip
  7.1.1.GA:
    release_date: 2014-03-26
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.3 Kepler.
    assets:
      jar_universal:
        size: 609mb
        name: Installer Jar (with EAP)
        type: jar
      standalone_jar:
        name: Installer Jar (Stand-alone)
        size: 482mb
        type: jar
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_jar.jar
      standalone_zip_update:
        name: Update Site Zip
        size: 713mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_update.zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 410mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_central.zip
      source:
        size: 6mb
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627

