name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
current_version: 8.0.0.GA
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
buzz_tags: jbds
guides:
  8.0.0_Release_Notes:
  Install_Red_Hat_JBoss_Developer_Studio:
  Start_Developing:
  Update_Red_Hat_JBoss_Developer_Studio:
default_download_artifact_type: jar_universal
description: 'A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.'
downloads:
  8.0.0.GA:
    release_date: 2014-10-21
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.4.1 Luna SR1.
    assets:
      jar_universal:
        name: Installer With EAP
        size: 687mb
        type: jar
      standalone_jar:
        name: Stand-alone Installer
        size: 548mb
        type: jar
      standalone_zip_update:
        name: Update Site
        size: 516mb
        type: zip
      standalone_zip_central:
        name: JBoss Central
        size: 304mb
        type: zip
      source:
        name: Source
        size: 8.5mb
        type: zip
  7.1.1.GA:
    release_date: 2014-03-26
    description: An IDE that gives you everything you need to build rich web and enterprise Java applications. Built on Eclipse 4.3 Kepler.
    assets:
      jar_universal:
        size: 609mb
        name: Installer Jar (with EAP)
        type: jar
      standalone_jar:
        name: Installer Jar (Stand-alone)
        size: 482mb
        type: jar
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_jar.jar
      standalone_zip_update:
        name: Update Site Zip
        size: 713mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_update.zip
      standalone_zip_central:
        name: JBoss Central Zip
        size: 410mb
        url: https://www.jboss.org/download-manager/file/jboss-devstudio-7.1.1.GA-standalone_universal-standalone_zip_central.zip
      source:
        size: 6mb
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627
