kramdown:
  :input: 'QuickStartParser'
download_manager_file_base_url: http://www-beta.jboss.org/download-manager/file
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US
product_forum_base_url: https://community.jboss.org/en/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
register_url: https://community.jboss.org/register.jspa

deploy_base: &deploy
  host: www@filemgmt.jboss.org
  cdn_host: www@filemgmt.jboss.org
  cdn_path: /static_htdocs/_root/common/www
  uncommitted: true

profile_base: &profile
  dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
  cdn_http_base: &cdn_http_base http://static.jboss.org/common/www 
  log_faraday: true
  minify: true
  deploy:
    <<: *deploy
  scss:
    :style: :compressed
    # Nice big hack:
    :cdn_http_base: http://static.jboss.org/common/www

profiles:
  development:
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    log_faraday: true

  staging: 
    <<: *profile
    base_url: http://www-stg.jboss.org
    deploy:
      <<: *deploy
      path: /stg_htdocs/www-stg
    
  beta:
    <<: *profile
    base_url: http://www-beta.jboss.org
    deploy:
      <<: *deploy
      path: /stg_htdocs/www-beta

  filemgmt:
    base_url: http://www-stg2.jboss.org/
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/

  production:
    dcp_base_url:

