kramdown:
  :input: 'QuickStartParser'
asciidoctor:
  :attributes:
    sectanchors: ''
download_manager_file_base_url: //www.jboss.org/download-manager/file/
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US/
product_forum_base_url: https://community.jboss.org/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
register_url: https://community.jboss.org/register.jspa
change_frequency: daily
disqus: jdf

deploy_base: &deploy
  host: www@filemgmt.jboss.org
  cdn_host: www@filemgmt.jboss.org
  cdn_path: /static_htdocs/www
  uncommitted: true

profile_base: &profile
  cdn_http_base: &cdn_http_base //static.jboss.org/www 
  cdn_out_dir: &cdn_out_dir _tmp
  cdn_version: &cdn_version true
  log_faraday: true
  push_to_searchisko: true
  minify: &minify true 
  metrics: true
  robots: true
  deploy:
    <<: *deploy
  scss:
    :style: :compressed
    # Nice big hack:
    :cdn_http_base: *cdn_http_base
    :cdn_out_dir: *cdn_out_dir
    :minify: *minify
    :cdn_version: *cdn_version

profiles:
  development:
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    dcp_base_protocol_relative_url: //dcpbeta-searchisko.rhcloud.com/
    log_faraday: true
    push_to_searchisko: false
    cdn_http_base: &dev_cdn_http_base http://localhost:4242/cdn
    cdn_out_dir: &dev_cdn_out_dir _site
    cdn_version: &dev_cdn_version false
    scss:
      # Nice big hack:
      :cdn_http_base: *dev_cdn_http_base
      :cdn_out_dir: *dev_cdn_out_dir
      :cdn_version: *dev_cdn_version

  staging: 
    <<: *profile
    dcp_base_protocol_relative_url: //dcpbeta-searchisko.rhcloud.com/
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    base_url: http://www-stg.jboss.org/
    deploy:
      <<: *deploy
      path: /stg_htdocs/www-stg
    
  production:
    <<: *profile
    base_url: http://www.jboss.org/
    dcp_base_protocol_relative_url: //dcp.jboss.org/
    dcp_base_url: http://dcp.jboss.org/
    require_tag: true
    robots: false
    deploy:
      <<: *deploy
      path: /www_htdocs/www

