name: Red Hat JBoss Data Grid 
abbreviated_name: JBoss Data Grid
forum_url: https://community.jboss.org/en/datagrid
current_version: 6.2.0.GA
intro_video: https://vimeo.com/95291413
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
  Developer_Guide:
  Getting_Started_Guide:
  Infinispan_Query_Guide:
default_download_artifact_type: zip
downloads:
  6.2.0.GA:
    release_date: 2014-01-15
    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
    assets:
      cppclient:
        name: CPP Client
        artifacts:
          win32:
            name: CPP Client Win32
            size: 19mb
          win64:
            name: CPP Client Win64
            size: 52mb
          rhel6_64:
            name: CPP Client RHEL6_64
            size: 153mb
          rhel5_64:
            name: CPP Client RHEL5_64
            size: 87mb
      zip_library:
        size: 41mb
        name: Zip (Data Grid Library)
      zip:
        size: 133mb
        name: Zip (Data Grid Server)
      release_notes:
      source:
        size: 9mb
#  6.1.0.GA:
#    release_date: 2013-03-20
#    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
#    assets:
#      zip_library:
#        size: 22mb
#        name: Zip (Data Grid Library)
#      zip:
#        size: 68mb
#        name: Zip (Data Grid Server)
#      release_notes:
#      source:
#        size: 8mb
#
#  6.0.1:
#    release_date: 2012-09-18
#    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
#    assets:
#      zip-library:
#        size: 14mb
#        name: Zip (Data Grid Library)
#      zip-server:
#        size: 67mb
#        name: Zip (Data Grid Server)
#  6.0.0:
#    release_date: 2012-06-15
#    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
#    assets:
#      zip-library:
#        size: 14mb
#        name: Zip (Data Grid Library)
#      zip-server:
#        size: 67mb
#        name: Zip (Data Grid Server)
#  6.2.0.BETA:
#    release_date: 2013-11-07
#    description: An in-memory distributed database, Red Hat JBoss Data Grid provides fast access to data and elastic scalability for large data volumes.
#    assets:
#      zip-cppclient-RHEL6_64:
#        size: 434kb
#        name: Zip (CPP Client RHEL6 64bit)
#      zip-library:
#        size: 41mb
#        name: Zip (Data Grid Library)
#      zip-server:
#        size: 133mb
#        name: Zip (Data Grid Server)
upstream_projects:
  - infinispan
  - jgroups
  - hibernate_subprojects_search
featured_items:
  - image_url: /images/design/devmats/developermaterials_datagrid.png
    title: 
    text: Get started with Data Grid with the basic Infinispan example

