:awestruct-layout: product-overview
:leveloffset: 1
:awestruct-interpolate: true

== Overview

Powerful, integrated, business event and business decision management.


== Features1

=== Business Rule Management

Leverage the power of declarative logic with business rules to build compact, fast and easy to understand business applications. +
Business experts and application developers in organizations of any size need to be able to model, automate, measure, and improve
their critical processes and policies. Red Hat(R) JBoss(R) BRMS makes it possible with fully integrated business rules management
and complex event processing (CEP). All through an open source subscription. Red Hat(R) JBoss(R) BRMS includes powerful new tools
for optimizing and scheduling business resources.

== Icon1

[.fa .fa-gear .fa-5x .fa-fw]#&nbsp;#


== Features2

=== Complex Event Processing

Detect, correlate and respond to events across multiple real-time data sources with the built-in Complex Event Processing extensions to the rule language and rule engine.

== Icon2
[.fa .fa-bell-o .fa-5x .fa-fw]#&nbsp;#


== Features3

=== Powerful toolsets

Create complete business applications with ease using comprehensive browser-based modeling tools for business rules, decision tables and scorecards.

== Icon3

[.fa .fa-wrench .fa-5x .fa-fw]#&nbsp;# 

== Detail

Learn how the Business Resource Planner can tackle a wide range of planning problems, from delivery routing to shift scheduling and
even managing compute resources in the cloud. 

#{video_thumb(video('https://vimeo.com/143059283'), 'video_thumb.html.slim')}

Download JBoss BRMS and explore the tools for authoring business rules, provided as both standalone web applications and plug-ins for JBoss Developer Studio.

=== Business Resource Planner

JBoss BRMS includes the Business Resource Planner, a toolkit designed to help developers construct applications that solve complex scheduling and resource optimization problems. Business Resource Planner offers a variety of algorithms that can quickly find good solutions to optimization problems that can be otherwise difficult, time-consuming and expensive to solve. No specific knowledge of optimization techniques is required in order to use Planner, making it easy to develop resource scheduling and planning applications without the need for specialized expertise and tools.

== Resources

https://github.com/jbossdemocentral?utf8=%E2%9C%93&query=brms-[Red Hat JBoss BRMS Product Demos]::
  JBoss BRMS demo repository with various projects and integration examples.

https://github.com/jbossdemocentral?utf8=%E2%9C%93&query=brmsPaaS[Red Hat JBoss BRMS PaaS Demo]::
  This was developed and have put together some automated cartridge installation projects that kick start you with pre-loaded demo projects.

http://www.schabell.org/search/label/Tips%26Tricks[BRMS Tips and Tricks]::
  This weeks tips and tricks article will help you to keep your JBoss BRMS running like a fine tuned machine.
